SELECT CUSTOMER.C_PHONE, LINEITEM.L_SHIPMODE, ORDERS.O_TOTALPRICE FROM CUSTOMER, ORDERS, LINEITEM WHERE ORDERS.O_COMMENT >= 'RIOUSLY AMONG THE REGULARLY REGULAR PAC' ORDER BY ORDERS.O_TOTALPRICE ASC;
