SELECT PART.P_TYPE, PARTSUPP.PS_SUPPLYCOST, MAX(PART.P_MFGR) FROM PARTSUPP JOIN PART ON PART.P_PARTKEY=PARTSUPP.PS_PARTKEY GROUP BY PART.P_TYPE, PARTSUPP.PS_SUPPLYCOST ORDER BY MAX(PART.P_MFGR) DESC;
