SELECT ORDERS.O_SHIPPRIORITY, CUSTOMER.C_NATIONKEY FROM ORDERS, CUSTOMER WHERE CUSTOMER.C_ADDRESS = '5IW,WROVNIKC3L7DWIUDGQNGSLBGOL6DC0' ORDER BY ORDERS.O_SHIPPRIORITY ASC, CUSTOMER.C_NATIONKEY DESC;
