SELECT PARTSUPP.PS_SUPPLYCOST, PART.P_PARTKEY FROM PART JOIN PARTSUPP ON PARTSUPP.PS_PARTKEY=PART.P_PARTKEY WHERE PARTSUPP.PS_AVAILQTY < 8501 ORDER BY PARTSUPP.PS_SUPPLYCOST ASC, PART.P_PARTKEY DESC;
