SELECT NATION.N_REGIONKEY, REGION.R_COMMENT FROM NATION JOIN REGION ON REGION.R_REGIONKEY=NATION.N_REGIONKEY WHERE REGION.R_NAME = '1995-01-03' ORDER BY NATION.N_REGIONKEY ASC, REGION.R_COMMENT DESC;
