SELECT NATION.N_COMMENT, REGION.R_NAME, COUNT(REGION.R_NAME) FROM NATION JOIN REGION ON REGION.R_REGIONKEY=NATION.N_REGIONKEY GROUP BY NATION.N_COMMENT, REGION.R_NAME HAVING COUNT(REGION.R_NAME) < 8;
