SELECT LINEITEM.L_COMMENT, ORDERS.O_ORDERKEY, AVG(ORDERS.O_SHIPPRIORITY) FROM LINEITEM, ORDERS GROUP BY LINEITEM.L_COMMENT, ORDERS.O_ORDERKEY ORDER BY LINEITEM.L_COMMENT DESC, ORDERS.O_ORDERKEY DESC;
