SELECT ORDERS.O_SHIPPRIORITY, CUSTOMER.C_CUSTKEY, LINEITEM.L_COMMENT, MAX(ORDERS.O_ORDERSTATUS) FROM CUSTOMER, ORDERS, LINEITEM GROUP BY ORDERS.O_SHIPPRIORITY, CUSTOMER.C_CUSTKEY, LINEITEM.L_COMMENT;
