SELECT LINEITEM.L_COMMENT, ORDERS.O_ORDERKEY FROM ORDERS JOIN LINEITEM ON LINEITEM.L_ORDERKEY=ORDERS.O_ORDERKEY WHERE ORDERS.O_CUSTKEY >= 14461 ORDER BY LINEITEM.L_COMMENT ASC, ORDERS.O_ORDERKEY ASC;
