SELECT PART.P_RETAILPRICE, PARTSUPP.PS_AVAILQTY, COUNT(PART.P_TYPE), MAX(PART.P_BRAND) FROM PART JOIN PARTSUPP ON PARTSUPP.PS_PARTKEY=PART.P_PARTKEY GROUP BY PART.P_RETAILPRICE, PARTSUPP.PS_AVAILQTY;
