SELECT NATION.N_NATIONKEY, REGION.R_NAME, COUNT(REGION.R_NAME) FROM REGION JOIN NATION ON NATION.N_REGIONKEY=REGION.R_REGIONKEY GROUP BY NATION.N_NATIONKEY, REGION.R_NAME ORDER BY REGION.R_NAME DESC;
